services:
  - type: web
    name: doc-ai-scheduler-ml
    env: python
    pythonVersion: 3.11.0
    buildCommand: python -m venv venv && . venv/bin/activate && pip install -r requirements.txt
    startCommand: . venv/bin/activate && python model.py
    envVars:
      - key: PORT
        value: 5050 