services:
  - type: web
    name: docai-backend
    env: docker
    repo: https://github.com/abeerrai01/DocAi-Scheduler
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: Backend
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://centerbeam.proxy.rlwy.net:24095/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: SnZgpgkVyPNWPIDuFRotlDIxRaUBluyJ
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.MySQLDialect 